-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R
ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID IN (
SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
    SELECT MAX(REVIEW_COUNT)
    FROM(
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )T
    )
)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC