-- 코드를 작성해주세요
SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, (T.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, D.ID
FROM ECOLI_DATA D
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR) T
ON T.YEAR = YEAR(D.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC 


-- 연도에서 가장 큰 것 고르고 뺀 값이 이어데브에로 가야 함.